"""Added registration_link to Event

Revision ID: de43af148dd1
Revises: 42d12d5b12ec
Create Date: 2025-02-28 14:56:11.626863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de43af148dd1'
down_revision = '42d12d5b12ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('registration_link')

    # ### end Alembic commands ###
