"""Added time column to Event table

Revision ID: f13ca6ae5df9
Revises: fd38598840f1
Create Date: 2025-02-28 14:16:36.664458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13ca6ae5df9'
down_revision = 'fd38598840f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('venue', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('registration_fees', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('rules')
        batch_op.drop_column('registration_fees')
        batch_op.drop_column('venue')
        batch_op.drop_column('time')

    # ### end Alembic commands ###
